INFO 2024-11-19 17:29:54,523 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 17:37:31,321 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 17:38:37,838 basehttp "POST /api/users/register/ HTTP/1.1" 201 82
INFO 2024-11-19 17:38:49,034 basehttp "POST /api/users/login/ HTTP/1.1" 200 529
WARNING 2024-11-19 17:39:33,656 log Unauthorized: /api/courses/
WARNING 2024-11-19 17:39:33,657 basehttp "GET /api/courses/ HTTP/1.1" 401 183
INFO 2024-11-19 17:39:43,190 basehttp "GET /api/courses/ HTTP/1.1" 200 598
INFO 2024-11-19 17:39:53,730 basehttp "POST /api/users/login/ HTTP/1.1" 200 529
INFO 2024-11-19 17:39:56,063 basehttp "POST /api/users/login/ HTTP/1.1" 200 523
INFO 2024-11-19 17:40:10,182 basehttp "GET /api/courses/enrollments/ HTTP/1.1" 200 244
WARNING 2024-11-19 18:03:28,411 log Not Found: /
WARNING 2024-11-19 18:03:28,411 basehttp "GET / HTTP/1.1" 404 2950
WARNING 2024-11-19 18:03:28,477 log Not Found: /favicon.ico
WARNING 2024-11-19 18:03:28,478 basehttp "GET /favicon.ico HTTP/1.1" 404 3001
INFO 2024-11-19 18:03:31,309 basehttp "GET /admin/ HTTP/1.1" 302 0
INFO 2024-11-19 18:03:31,410 basehttp "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4164
INFO 2024-11-19 18:03:31,430 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2024-11-19 18:03:31,430 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2024-11-19 18:03:31,431 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2024-11-19 18:03:31,432 basehttp "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO 2024-11-19 18:03:31,432 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2024-11-19 18:03:31,433 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2024-11-19 18:03:31,436 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2024-11-19 18:03:41,207 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4328
INFO 2024-11-19 18:03:47,384 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4328
INFO 2024-11-19 18:03:58,138 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4328
INFO 2024-11-19 18:04:59,096 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 18:05:05,985 basehttp "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2024-11-19 18:05:06,042 basehttp "GET /admin/ HTTP/1.1" 200 10018
INFO 2024-11-19 18:05:06,059 basehttp "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2024-11-19 18:05:06,063 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2024-11-19 18:05:06,064 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2024-11-19 18:05:12,644 basehttp "GET /admin/django_celery_beat/periodictask/ HTTP/1.1" 200 13713
INFO 2024-11-19 18:05:12,660 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2024-11-19 18:05:12,660 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2024-11-19 18:05:12,662 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2024-11-19 18:05:12,664 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2024-11-19 18:05:12,665 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2024-11-19 18:05:12,666 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2024-11-19 18:05:12,669 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2024-11-19 18:05:12,670 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2024-11-19 18:05:12,694 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2024-11-19 18:05:12,714 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2024-11-19 18:05:12,720 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2024-11-19 18:05:12,730 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2024-11-19 18:05:12,747 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2024-11-19 18:05:12,747 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2024-11-19 18:05:19,175 basehttp "GET /admin/django_celery_beat/solarschedule/ HTTP/1.1" 200 10326
INFO 2024-11-19 18:05:19,193 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2024-11-19 18:05:19,771 basehttp "GET /admin/django_celery_beat/intervalschedule/ HTTP/1.1" 200 10317
INFO 2024-11-19 18:05:19,788 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2024-11-19 18:05:20,465 basehttp "GET /admin/django_celery_beat/crontabschedule/ HTTP/1.1" 200 10310
INFO 2024-11-19 18:05:20,476 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2024-11-19 18:05:20,922 basehttp "GET /admin/django_celery_beat/clockedschedule/ HTTP/1.1" 200 10308
INFO 2024-11-19 18:05:20,939 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2024-11-19 18:05:23,521 basehttp "GET /admin/auth/group/ HTTP/1.1" 200 10581
INFO 2024-11-19 18:05:23,536 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2024-11-19 18:05:24,712 basehttp "GET /admin/students/student/ HTTP/1.1" 200 13469
INFO 2024-11-19 18:05:24,726 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 3342
INFO 2024-11-19 18:10:27,395 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\miniproj2\StudentManagementSystem\settings.py changed, reloading.
INFO 2024-11-19 18:10:28,458 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 18:40:03,231 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 18:50:39,092 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 18:51:52,960 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 18:54:10,942 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 19:02:01,928 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\miniproj2\StudentManagementSystem\settings.py changed, reloading.
INFO 2024-11-19 19:02:03,149 autoreload Watching for file changes with StatReloader
WARNING 2024-11-19 19:23:43,050 log Forbidden: /api/courses/
WARNING 2024-11-19 19:25:43,442 log Forbidden: /api/courses/
WARNING 2024-11-19 19:27:00,645 log Forbidden: /api/courses/
INFO 2024-11-19 19:28:52,819 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 19:28:54,819 basehttp "POST /api/courses/ HTTP/1.1" 201 59
WARNING 2024-11-19 19:29:27,318 log Forbidden: /api/courses/
WARNING 2024-11-19 19:30:36,770 log Forbidden: /api/courses/
INFO 2024-11-19 19:31:34,949 autoreload Watching for file changes with StatReloader
ERROR 2024-11-19 19:31:41,566 log Internal Server Error: /api/users/register/
Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: students_student.email

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\generics.py", line 194, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\miniproj2\users\serializers.py", line 19, in create
    user = User.objects.create_user(**validated_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\contrib\auth\models.py", line 162, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\contrib\auth\models.py", line 156, in _create_user
    user.save(using=self._db)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\contrib\auth\base_user.py", line 62, in save
    super().save(*args, **kwargs)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1012, in save_base
    post_save.send(
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\miniproj2\students\models.py", line 19, in create_student_profile
    Student.objects.create(
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: students_student.email
ERROR 2024-11-19 19:31:41,583 basehttp "POST /api/users/register/ HTTP/1.1" 500 245835
WARNING 2024-11-19 19:31:56,673 log Bad Request: /api/users/register/
WARNING 2024-11-19 19:31:56,674 basehttp "POST /api/users/register/ HTTP/1.1" 400 58
INFO 2024-11-19 19:32:03,489 basehttp "POST /api/users/register/ HTTP/1.1" 201 83
WARNING 2024-11-19 19:34:13,913 log Forbidden: /api/courses/
WARNING 2024-11-19 19:35:26,275 log Forbidden: /api/courses/
WARNING 2024-11-19 19:39:59,063 log Forbidden: /api/courses/
WARNING 2024-11-19 19:44:11,206 log Forbidden: /api/courses/
INFO 2024-11-19 19:44:11,225 views Cache miss for student profile: 2
ERROR 2024-11-19 19:44:11,247 log Internal Server Error: /api/students/profile/2/
Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\generics.py", line 212, in get
    return self.retrieve(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\miniproj2\students\views.py", line 58, in retrieve
    return Response(serializer.data)
           ^^^^^^^^
NameError: name 'Response' is not defined
WARNING 2024-11-19 19:44:41,849 log Forbidden: /api/courses/
INFO 2024-11-19 19:44:41,868 views Cache miss for student profile: 2
INFO 2024-11-19 19:44:41,870 views Cache hit for student profile: 2
WARNING 2024-11-19 20:08:56,673 log Forbidden: /api/courses/
INFO 2024-11-19 20:08:56,690 views Cache miss for student profile: 2
INFO 2024-11-19 20:08:56,693 views Cache hit for student profile: 2
INFO 2024-11-19 20:10:00,504 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 20:10:20,715 autoreload Watching for file changes with StatReloader
WARNING 2024-11-19 20:10:31,399 log Unauthorized: /api/students/all_profiles/
WARNING 2024-11-19 20:10:31,400 basehttp "GET /api/students/all_profiles/ HTTP/1.1" 401 183
INFO 2024-11-19 20:10:46,841 basehttp "GET /api/students/all_profiles/ HTTP/1.1" 200 52
ERROR 2024-11-19 20:11:02,306 log Internal Server Error: /api/courses/enrollments/
Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\generics.py", line 243, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\generics.py", line 154, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django_filters\rest_framework\backends.py", line 68, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django_filters\rest_framework\backends.py", line 20, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django_filters\rest_framework\backends.py", line 51, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django_filters\filterset.py", line 78, in __new__
    new_class.base_filters = new_class.get_filters()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django_filters\filterset.py", line 367, in get_filters
    raise TypeError(
TypeError: 'Meta.fields' must not contain non-model field names: name
ERROR 2024-11-19 20:11:02,313 basehttp "GET /api/courses/enrollments/ HTTP/1.1" 500 132098
INFO 2024-11-19 20:11:31,630 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\miniproj2\courses\views.py changed, reloading.
INFO 2024-11-19 20:11:32,640 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 20:11:34,841 basehttp "GET /api/courses/enrollments/ HTTP/1.1" 200 294
INFO 2024-11-19 20:11:46,871 basehttp "GET /api/students/all_profiles/ HTTP/1.1" 200 52
WARNING 2024-11-19 20:11:54,084 log Unauthorized: /api/students/profile/1/
WARNING 2024-11-19 20:11:54,085 basehttp "GET /api/students/profile/1/ HTTP/1.1" 401 183
INFO 2024-11-19 20:11:59,893 views Cache miss for student profile: 1
INFO 2024-11-19 20:11:59,896 basehttp "GET /api/students/profile/1/ HTTP/1.1" 200 161
INFO 2024-11-19 20:12:07,748 basehttp "GET /api/students/all_profiles/ HTTP/1.1" 200 52
WARNING 2024-11-19 20:13:09,587 log Unauthorized: /api/courses/
WARNING 2024-11-19 20:13:09,588 basehttp "GET /api/courses/ HTTP/1.1" 401 183
INFO 2024-11-19 20:13:24,696 basehttp "GET /api/courses/ HTTP/1.1" 200 607
INFO 2024-11-19 20:13:34,983 basehttp "GET /api/courses/?page=2 HTTP/1.1" 200 223
INFO 2024-11-19 20:14:15,950 basehttp "GET /api/students/all_profiles/ HTTP/1.1" 200 52
INFO 2024-11-19 20:14:45,399 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\miniproj2\students\views.py changed, reloading.
INFO 2024-11-19 20:14:46,656 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 20:15:04,350 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\miniproj2\students\views.py changed, reloading.
INFO 2024-11-19 20:15:05,396 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 20:15:09,331 basehttp "GET /api/students/all_profiles/ HTTP/1.1" 200 52
INFO 2024-11-19 20:15:17,044 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\miniproj2\students\views.py changed, reloading.
INFO 2024-11-19 20:15:18,121 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 20:15:22,202 basehttp "GET /api/students/all_profiles/ HTTP/1.1" 200 52
INFO 2024-11-19 20:15:52,215 basehttp "POST /api/users/login/ HTTP/1.1" 200 523
INFO 2024-11-19 20:16:04,599 basehttp "GET /api/students/all_profiles/ HTTP/1.1" 200 713
INFO 2024-11-19 20:16:16,813 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\miniproj2\students\views.py changed, reloading.
INFO 2024-11-19 20:16:17,873 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 20:16:18,493 basehttp "GET /api/students/all_profiles/ HTTP/1.1" 200 713
INFO 2024-11-19 20:17:42,973 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\miniproj2\students\views.py changed, reloading.
INFO 2024-11-19 20:17:43,927 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 20:17:48,222 basehttp "GET /api/students/all_profiles/ HTTP/1.1" 200 713
INFO 2024-11-19 20:18:35,133 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\miniproj2\students\views.py changed, reloading.
INFO 2024-11-19 20:18:36,154 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 20:18:39,030 basehttp "GET /api/students/all_profiles/ HTTP/1.1" 200 663
INFO 2024-11-19 20:19:41,279 autoreload Watching for file changes with StatReloader
ERROR 2024-11-19 20:22:38,387 log Internal Server Error: /api/grades/
Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: grades_grade.course_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: grades_grade.course_id
ERROR 2024-11-19 20:22:38,401 basehttp "POST /api/grades/ HTTP/1.1" 500 214681
ERROR 2024-11-19 20:23:08,780 log Internal Server Error: /api/grades/
Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: grades_grade.course_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: grades_grade.course_id
ERROR 2024-11-19 20:23:08,791 basehttp "POST /api/grades/ HTTP/1.1" 500 214705
ERROR 2024-11-19 20:23:27,970 log Internal Server Error: /api/grades/
Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: grades_grade.course_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: grades_grade.course_id
ERROR 2024-11-19 20:23:27,982 basehttp "POST /api/grades/ HTTP/1.1" 500 214705
INFO 2024-11-19 20:27:15,760 basehttp "GET /api/courses/ HTTP/1.1" 200 607
INFO 2024-11-19 20:27:22,960 basehttp "GET /api/courses/?page=2 HTTP/1.1" 200 223
ERROR 2024-11-19 20:27:44,250 log Internal Server Error: /api/grades/
Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: grades_grade.course_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: grades_grade.course_id
ERROR 2024-11-19 20:27:44,261 basehttp "POST /api/grades/ HTTP/1.1" 500 214705
INFO 2024-11-19 20:28:21,513 views Student teststudent1 enrolled in course test
INFO 2024-11-19 20:28:21,514 basehttp "POST /api/courses/enrollments/ HTTP/1.1" 201 80
ERROR 2024-11-19 20:28:25,890 log Internal Server Error: /api/grades/
Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: grades_grade.course_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: grades_grade.course_id
ERROR 2024-11-19 20:28:25,901 basehttp "POST /api/grades/ HTTP/1.1" 500 214705
ERROR 2024-11-19 20:28:38,480 log Internal Server Error: /api/grades/
Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: grades_grade.course_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: grades_grade.course_id
ERROR 2024-11-19 20:28:38,492 basehttp "POST /api/grades/ HTTP/1.1" 500 214681
ERROR 2024-11-19 20:28:48,589 log Internal Server Error: /api/grades/
Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: grades_grade.course_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: grades_grade.course_id
ERROR 2024-11-19 20:28:48,601 basehttp "POST /api/grades/ HTTP/1.1" 500 214757
INFO 2024-11-19 20:29:45,999 basehttp "GET /api/students/all_profiles/ HTTP/1.1" 200 663
ERROR 2024-11-19 20:30:19,604 log Internal Server Error: /api/grades/
Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: grades_grade.course_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: grades_grade.course_id
ERROR 2024-11-19 20:30:19,614 basehttp "POST /api/grades/ HTTP/1.1" 500 214681
ERROR 2024-11-19 20:30:37,934 log Internal Server Error: /api/grades/
Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: grades_grade.course_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\djangoceleryenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: grades_grade.course_id
ERROR 2024-11-19 20:30:37,946 basehttp "POST /api/grades/ HTTP/1.1" 500 214693
INFO 2024-11-19 20:32:05,675 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\miniproject2\MiniProject2\miniproj2\grades\serializers.py changed, reloading.
INFO 2024-11-19 20:32:08,881 autoreload Watching for file changes with StatReloader
INFO 2024-11-19 20:32:21,340 basehttp "POST /api/grades/ HTTP/1.1" 201 76
INFO 2024-11-19 20:32:40,490 views Student teststudent2 enrolled in course test
INFO 2024-11-19 20:32:40,492 basehttp "POST /api/courses/enrollments/ HTTP/1.1" 201 80
INFO 2024-11-19 20:32:47,996 basehttp "POST /api/grades/ HTTP/1.1" 201 76
INFO 2024-11-19 20:33:42,377 basehttp "GET /api/students/all_profiles/ HTTP/1.1" 200 663
